const columnWeeklyCall = [
  {
    id: "id",
    numeric: true,
    disablePadding: true,
    label: "",
    minWidth: 20,
  },
  {
    id: "caller",
    numeric: false,
    disablePadding: true,
    label: "Caller",
    minWidth: 120,
  },
  {
    id: "totalCall",
    numeric: true,
    disablePadding: true,
    label: "TotalCall",
    minWidth: 90,
  },
  {
    id: "1",
    numeric: true,
    disablePadding: true,
    label: "1",
    minWidth: 20,
  },
  {
    id: "2",
    numeric: true,
    disablePadding: true,
    label: "2",
    minWidth: 20,
  },
  {
    id: "3",
    numeric: true,
    disablePadding: true,
    label: "3",
    minWidth: 20,
  },
  {
    id: "4",
    numeric: true,
    disablePadding: true,
    label: "4",
    minWidth: 20,
  },
  {
    id: "5",
    numeric: true,
    disablePadding: true,
    label: "5",
    minWidth: 20,
  },
  {
    id: "6",
    numeric: true,
    disablePadding: true,
    label: "6",
    minWidth: 20,
  },
  {
    id: "7",
    numeric: true,
    disablePadding: true,
    label: "7",
    minWidth: 20,
  },
  {
    id: "8",
    numeric: true,
    disablePadding: true,
    label: "8",
    minWidth: 20,
  },
  {
    id: "9",
    numeric: true,
    disablePadding: true,
    label: "9",
    minWidth: 20,
  },
  {
    id: "10",
    numeric: true,
    disablePadding: true,
    label: "10",
    minWidth: 20,
  },
  {
    id: "11",
    numeric: true,
    disablePadding: true,
    label: "11",
    minWidth: 20,
  },
  {
    id: "12",
    numeric: true,
    disablePadding: true,
    label: "12",
    minWidth: 20,
  },
  {
    id: "13",
    numeric: true,
    disablePadding: true,
    label: "13",
    minWidth: 20,
  },
  {
    id: "14",
    numeric: true,
    disablePadding: true,
    label: "14",
    minWidth: 20,
  },
  {
    id: "15",
    numeric: true,
    disablePadding: true,
    label: "15",
    minWidth: 20,
  },
  {
    id: "16",
    numeric: true,
    disablePadding: true,
    label: "16",
    minWidth: 20,
  },
  {
    id: "17",
    numeric: true,
    disablePadding: true,
    label: "17",
    minWidth: 20,
  },
  {
    id: "18",
    numeric: true,
    disablePadding: true,
    label: "18",
    minWidth: 20,
  },
  {
    id: "19",
    numeric: true,
    disablePadding: true,
    label: "19",
    minWidth: 20,
  },
  {
    id: "20",
    numeric: true,
    disablePadding: true,
    label: "20",
    minWidth: 20,
  },
  {
    id: "21",
    numeric: true,
    disablePadding: true,
    label: "21",
    minWidth: 20,
  },
  {
    id: "22",
    numeric: true,
    disablePadding: true,
    label: "22",
    minWidth: 20,
  },
  {
    id: "23",
    numeric: true,
    disablePadding: true,
    label: "23",
    minWidth: 20,
  },
  {
    id: "24",
    numeric: true,
    disablePadding: true,
    label: "24",
    minWidth: 20,
  },
  {
    id: "25",
    numeric: true,
    disablePadding: true,
    label: "25",
    minWidth: 20,
  },
  {
    id: "26",
    numeric: true,
    disablePadding: true,
    label: "26",
    minWidth: 20,
  },
  {
    id: "27",
    numeric: true,
    disablePadding: true,
    label: "27",
    minWidth: 20,
  },
  {
    id: "28",
    numeric: true,
    disablePadding: true,
    label: "28",
    minWidth: 20,
  },
  {
    id: "29",
    numeric: true,
    disablePadding: true,
    label: "29",
    minWidth: 20,
  },
  {
    id: "30",
    numeric: true,
    disablePadding: true,
    label: "30",
    minWidth: 20,
  },
  {
    id: "31",
    numeric: true,
    disablePadding: true,
    label: "31",
    minWidth: 20,
  },
  {
    id: "32",
    numeric: true,
    disablePadding: true,
    label: "32",
    minWidth: 20,
  },
  {
    id: "33",
    numeric: true,
    disablePadding: true,
    label: "33",
    minWidth: 20,
  },
  {
    id: "34",
    numeric: true,
    disablePadding: true,
    label: "34",
    minWidth: 20,
  },
  {
    id: "35",
    numeric: true,
    disablePadding: true,
    label: "35",
    minWidth: 20,
  },
  {
    id: "36",
    numeric: true,
    disablePadding: true,
    label: "36",
    minWidth: 20,
  },
  {
    id: "37",
    numeric: true,
    disablePadding: true,
    label: "37",
    minWidth: 20,
  },
  {
    id: "38",
    numeric: true,
    disablePadding: true,
    label: "38",
    minWidth: 20,
  },
  {
    id: "39",
    numeric: true,
    disablePadding: true,
    label: "39",
    minWidth: 20,
  },
  {
    id: "40",
    numeric: true,
    disablePadding: true,
    label: "40",
    minWidth: 20,
  },
  {
    id: "41",
    numeric: true,
    disablePadding: true,
    label: "41",
    minWidth: 20,
  },
  {
    id: "42",
    numeric: true,
    disablePadding: true,
    label: "42",
    minWidth: 20,
  },
  {
    id: "43",
    numeric: true,
    disablePadding: true,
    label: "43",
    minWidth: 20,
  },
  {
    id: "44",
    numeric: true,
    disablePadding: true,
    label: "44",
    minWidth: 20,
  },
  {
    id: "45",
    numeric: true,
    disablePadding: true,
    label: "45",
    minWidth: 20,
  },
  {
    id: "46",
    numeric: true,
    disablePadding: true,
    label: "46",
    minWidth: 20,
  },
  {
    id: "47",
    numeric: true,
    disablePadding: true,
    label: "47",
    minWidth: 20,
  },
  {
    id: "48",
    numeric: true,
    disablePadding: true,
    label: "48",
    minWidth: 20,
  },
  {
    id: "49",
    numeric: true,
    disablePadding: true,
    label: "49",
    minWidth: 20,
  },
  {
    id: "50",
    numeric: true,
    disablePadding: true,
    label: "50",
    minWidth: 20,
  },
  {
    id: "51",
    numeric: true,
    disablePadding: true,
    label: "51",
    minWidth: 20,
  },
  {
    id: "52",
    numeric: true,
    disablePadding: true,
    label: "52",
    minWidth: 20,
  },
  {
    id: "53",
    numeric: true,
    disablePadding: true,
    label: "53",
    minWidth: 20,
  },
];

export default columnWeeklyCall;
