const columnHourlyImeiCalled = [
  {
    id: "id",
    numeric: true,
    disablePadding: true,
    label: "",
    minWidth: 20,
  },
  {
    id: "called",
    numeric: true,
    disablePadding: true,
    label: "Called Imei",
    minWidth: 120,
  },
  {
    id: "0",
    numeric: true,
    disablePadding: true,
    label: "0",
    minWidth: 20,
  },
  {
    id: "1",
    numeric: true,
    disablePadding: true,
    label: "1",
    minWidth: 20,
  },
  {
    id: "2",
    numeric: true,
    disablePadding: true,
    label: "2",
    minWidth: 20,
  },
  {
    id: "3",
    numeric: true,
    disablePadding: true,
    label: "3",
    minWidth: 20,
  },
  {
    id: "4",
    numeric: true,
    disablePadding: true,
    label: "4",
    minWidth: 20,
  },
  {
    id: "5",
    numeric: true,
    disablePadding: true,
    label: "5",
    minWidth: 20,
  },
  {
    id: "6",
    numeric: true,
    disablePadding: true,
    label: "6",
    minWidth: 20,
  },
  {
    id: "7",
    numeric: true,
    disablePadding: true,
    label: "7",
    minWidth: 20,
  },
  {
    id: "8",
    numeric: true,
    disablePadding: true,
    label: "8",
    minWidth: 20,
  },
  {
    id: "9",
    numeric: true,
    disablePadding: true,
    label: "9",
    minWidth: 20,
  },
  {
    id: "10",
    numeric: true,
    disablePadding: true,
    label: "10",
    minWidth: 20,
  },
  {
    id: "11",
    numeric: true,
    disablePadding: true,
    label: "11",
    minWidth: 20,
  },
  {
    id: "12",
    numeric: true,
    disablePadding: true,
    label: "12",
    minWidth: 20,
  },
  {
    id: "13",
    numeric: true,
    disablePadding: true,
    label: "13",
    minWidth: 20,
  },
  {
    id: "14",
    numeric: true,
    disablePadding: true,
    label: "14",
    minWidth: 20,
  },
  {
    id: "15",
    numeric: true,
    disablePadding: true,
    label: "15",
    minWidth: 20,
  },
  {
    id: "16",
    numeric: true,
    disablePadding: true,
    label: "16",
    minWidth: 20,
  },
  {
    id: "17",
    numeric: true,
    disablePadding: true,
    label: "17",
    minWidth: 20,
  },
  {
    id: "18",
    numeric: true,
    disablePadding: true,
    label: "18",
    minWidth: 20,
  },
  {
    id: "19",
    numeric: true,
    disablePadding: true,
    label: "19",
    minWidth: 20,
  },
  {
    id: "20",
    numeric: true,
    disablePadding: true,
    label: "20",
    minWidth: 20,
  },
  {
    id: "21",
    numeric: true,
    disablePadding: true,
    label: "21",
    minWidth: 20,
  },
  {
    id: "22",
    numeric: true,
    disablePadding: true,
    label: "22",
    minWidth: 20,
  },
  {
    id: "23",
    numeric: true,
    disablePadding: true,
    label: "23",
    minWidth: 20,
  },
  {
    id: "24",
    numeric: true,
    disablePadding: true,
    label: "24",
    minWidth: 20,
  },

  {
    id: "totalCall",
    numeric: true,
    disablePadding: true,
    label: "TotalCall",
    minWidth: 90,
  },
];

export default columnHourlyImeiCalled;
