const columnMonthlyCall = [
  {
    id: "id",
    numeric: true,
    disablePadding: true,
    label: "",
    minWidth: 20,
  },
  {
    id: "caller",
    numeric: false,
    disablePadding: true,
    label: "Caller",
    minWidth: 120,
  },
  {
    id: "totalCall",
    numeric: true,
    disablePadding: true,
    label: "TotalCall",
    minWidth: 90,
  },
  {
    id: "1",
    numeric: true,
    disablePadding: true,
    label: "Jan",
    minWidth: 20,
  },
  {
    id: "2",
    numeric: true,
    disablePadding: true,
    label: "Feb",
    minWidth: 20,
  },
  {
    id: "3",
    numeric: true,
    disablePadding: true,
    label: "Mar",
    minWidth: 20,
  },
  {
    id: "4",
    numeric: true,
    disablePadding: true,
    label: "Apr",
    minWidth: 20,
  },
  {
    id: "5",
    numeric: true,
    disablePadding: true,
    label: "May",
    minWidth: 20,
  },
  {
    id: "6",
    numeric: true,
    disablePadding: true,
    label: "Jun",
    minWidth: 20,
  },
  {
    id: "7",
    numeric: true,
    disablePadding: true,
    label: "Jul",
    minWidth: 20,
  },
  {
    id: "8",
    numeric: true,
    disablePadding: true,
    label: "Aug",
    minWidth: 20,
  },
  {
    id: "9",
    numeric: true,
    disablePadding: true,
    label: "Sep",
    minWidth: 20,
  },
  {
    id: "10",
    numeric: true,
    disablePadding: true,
    label: "Oct",
    minWidth: 20,
  },
  {
    id: "11",
    numeric: true,
    disablePadding: true,
    label: "Nov",
    minWidth: 20,
  },
  {
    id: "12",
    numeric: true,
    disablePadding: true,
    label: "Dec",
    minWidth: 20,
  },
];

export default columnMonthlyCall;
