const columnMonthlyCall = [
  {
    id: "id",
    numeric: true,
    disablePadding: true,
    label: "",
    minWidth: 20,
  },
  {
    id: "caller",
    numeric: true,
    disablePadding: true,
    label: "Caller",
    minWidth: 120,
  },
  {
    id: "1",
    numeric: true,
    disablePadding: true,
    label: "1",
    minWidth: 20,
  },
  {
    id: "2",
    numeric: true,
    disablePadding: true,
    label: "2",
    minWidth: 20,
  },
  {
    id: "3",
    numeric: true,
    disablePadding: true,
    label: "3",
    minWidth: 20,
  },
  {
    id: "4",
    numeric: true,
    disablePadding: true,
    label: "4",
    minWidth: 20,
  },
  {
    id: "5",
    numeric: true,
    disablePadding: true,
    label: "5",
    minWidth: 20,
  },
  {
    id: "6",
    numeric: true,
    disablePadding: true,
    label: "6",
    minWidth: 20,
  },
  {
    id: "7",
    numeric: true,
    disablePadding: true,
    label: "7",
    minWidth: 20,
  },
  {
    id: "8",
    numeric: true,
    disablePadding: true,
    label: "8",
    minWidth: 20,
  },
  {
    id: "9",
    numeric: true,
    disablePadding: true,
    label: "9",
    minWidth: 20,
  },
  {
    id: "10",
    numeric: true,
    disablePadding: true,
    label: "10",
    minWidth: 20,
  },
  {
    id: "11",
    numeric: true,
    disablePadding: true,
    label: "11",
    minWidth: 20,
  },
  {
    id: "12",
    numeric: true,
    disablePadding: true,
    label: "12",
    minWidth: 20,
  },

  {
    id: "totalCall",
    numeric: true,
    disablePadding: true,
    label: "TotalCall",
    minWidth: 90,
  },
];

export default columnMonthlyCall;
